# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the action will run. 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build hello-docker
      run: |
        docker build -t hello-docker .
    - name: docker run
      run: |
        docker run hello-docker       
    - name: docker push
      run: |
        docker push hello-docker
