# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the action will run. 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build hello-docker
      run: |
        docker build -t akshatgurnani/hello-docker .
#     - name: docker run
#       run: |
#         docker run akshatgurnani/hello-docker
    
#     - name: docker change tag
#       run: |
#         docker tag akshatgurnani/hello-docker:latest docker.pkg.github.com/akshatgurnani/hello-docker/hello-docker:v1
    
#     - name: docker push pkg
#       run: |
#         docker push docker.pkg.github.com/akshatgurnani/hello-docker/hello-docker:v1
    
    - name: docker push
      run: |
        docker push akshatgurnani/hello-docker
